import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from './components/Navbar';  // Importa el Navbar
import Footer from './components/Footer';  // Importa el Footer
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />   {/* Añade el Navbar globalmente */}
        {children}
        <Footer />   {/* Añade el Footer globalmente */}
      </body>
    </html>
  );
}
